modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="grassdiamond"
version="1.0.0"
displayName="Grass Diamond"
description="Primești un diamant la click dreapta pe grass block."
authors="Antoniosebyy"
